<?php

use Senac\Projeto\Controllers\{AgendamentoController\DeleteAgendamentoController,
    AgendamentoController\EditAgendamentoController,
    AgendamentoController\EditFormAgendamentoController,
    AgendamentoController\NewAgendamentoController,
    AgradecimentoViewController,
    BarbeiroController\AdmBarbeiroController,
    BarbeiroController\DeleteUsuarioController,
    BarbeiroController\FormBarbeiroController,
    BarbeiroController\FormBarbeiroLoginController,
    BarbeiroController\LoginBarberController,
    BarbeiroController\LogoutBarbeiroController,
    BarbeiroController\NewBarbeiroController,
    BarbeiroController\UsuariosCadastradosController,
    EmailController,
    HomeViewController,
    ServicoController\DeleteServicoController,
    ServicoController\EditServicoController,
    ServicoController\EditServicoFormController,
    ServicoController\FormServicoController,
    ServicoController\ListServicoController,
    ServicoController\NewServicoController,
    UsuariosController\DashboardViewController,
    UsuariosController\EditPerfilController,
    UsuariosController\EditPerfilForm,
    UsuariosController\FormLoginUsuarioController,
    UsuariosController\FormUsuarioController,
    UsuariosController\LoginUsuarioController,
    UsuariosController\NewUsuarioController,
    UsuariosController\SessionUsuarioController,
    UsuariosController\VerUsuarioController};

return [
    'GET|/' => HomeViewController::class,
    'POST|/' => EmailController::class,
    'GET|/login' => FormLoginUsuarioController::class,
    'POST|/login' => LoginUsuarioController::class,
    'GET|/cadastro-usuario' => FormUsuarioController::class,
    'POST|/cadastro-usuario' => NewUsuarioController::class,
    'GET|/login-barbeiro' => FormBarbeiroLoginController::class,
    'POST|/login-barbeiro' => LoginBarberController::class,
    'GET|/cadastro-barbeiro' => FormBarbeiroController::class,
    'POST|/cadastro-barbeiro' => NewBarbeiroController::class,
    'GET|/logout' => SessionUsuarioController::class,
    'GET|/sair-barbeiro' => LogoutBarbeiroController::class,
    'GET|/dashboard' => DashboardViewController::class,
    'POST|/dashboard' => NewAgendamentoController::class,
    'GET|/administracao' => AdmBarbeiroController::class,
    'GET|/cadastro-servico' => FormServicoController::class,
    'POST|/cadastro-servico' => NewServicoController::class,
    'GET|/ver-usuario' => VerUsuarioController::class,
    'GET|/editar-usuario' => EditPerfilForm::class,
    'POST|/editar-usuario' => EditPerfilController::class,
    'GET|/usuarios-cadastrados' => UsuariosCadastradosController::class,
    'GET|/excluir-usuario' => DeleteUsuarioController::class,
    'GET|/excluir-agendamento' => DeleteAgendamentoController::class,
    'GET|/edit-agendamento' => EditFormAgendamentoController::class,
    'POST|/edit-agendamento' => EditAgendamentoController::class,
    'GET|/servicos' => ListServicoController::class,
    'GET|/delete-servico' => DeleteServicoController::class,
    'GET|/edit-servico' => EditServicoFormController::class,
    'POST|/edit-servico' => EditServicoController::class,
    'GET|/agradecimento' => AgradecimentoViewController::class
];
